# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Kernel": "00_kernel.ipynb",
         "LinearKernel": "00_kernel.ipynb",
         "PolynomialKernel": "00_kernel.ipynb",
         "HomogeneousPolynomialKernel": "00_kernel.ipynb",
         "GaussianKernel": "00_kernel.ipynb",
         "HyperbolicKernel": "00_kernel.ipynb",
         "PrecomputedKernel": "00_kernel.ipynb"}

modules = ["kernel.py"]

doc_url = "https://dariomalchiodi.github.io/mulearn/"

git_url = "https://github.com/dariomalchiodi/mulearn/tree/master/"

def custom_doc_links(name): return None
